package com.akinnova.BookReviewMav.enums;

public enum Category {
    EDIT , PROOFREADING, REFERENCING, COPYRIGHTING, RESEARCH, ACADEMIC_PROJECT, BOOK_WRITING, BUSINESS_PLAN,
    RESUME_WRITING, SCRIPT_WRITING
}
